apiVersion: fn.kpt.dev/v1alpha1
kind: RenderHelmChart
metadata:
  name: render-chart
  annotations:
    config.kubernetes.io/local-config: "true"
helmCharts:
- chartArgs:
    name: metrics-server
    version: 3.8.2
    repo: https://kubernetes-sigs.github.io/metrics-server/
  templateOptions:
    releaseName: metrics-server
    namespace: metrics-server
    values:
      valuesFile: values-metrics-server.yaml
