# KRM function 'render-helm-chart' format
# See
#  - https://catalog.kpt.dev/render-helm-chart/v0.1/?id=render-helm-chart
#  - https://github.com/GoogleContainerTools/kpt-functions-catalog/tree/master/functions/go/render-helm-chart

helmCharts:
- chartArgs:
    name: prometheus
    version: 15.5.3
    repo: https://prometheus-community.github.io/helm-charts
  templateOptions:
    releaseName: prometheus
    namespace: monitoring-prometheus
    values:
      valuesInline:
        rbac.create: true
        alertmanager.enabled: false
        pushgateway.enabled: false,
        networkPolicy.enabled: true
        server.retention: '7d'
